--
-- PostgreSQL database dump
--

\restrict gjw00SRBVXZcIjGgPwKPct40qQ8iWOuEt7DKhWvgLBa3JUnGvoStSpv5vKeSOXb

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-04-06 15:25:27

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 33042)
-- Name: chapters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chapters (
    chapter_id integer NOT NULL,
    subject_id integer,
    chapter_name character varying(150) NOT NULL,
    order_num integer DEFAULT 1,
    description text,
    is_locked boolean DEFAULT false
);


ALTER TABLE public.chapters OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 33041)
-- Name: chapters_chapter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.chapters_chapter_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.chapters_chapter_id_seq OWNER TO postgres;

--
-- TOC entry 5161 (class 0 OID 0)
-- Dependencies: 223
-- Name: chapters_chapter_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.chapters_chapter_id_seq OWNED BY public.chapters.chapter_id;


--
-- TOC entry 229 (class 1259 OID 33092)
-- Name: practice_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.practice_sessions (
    session_id integer NOT NULL,
    user_id integer,
    subject_id integer,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    chapter_id integer,
    total_q integer DEFAULT 0,
    correct_count integer DEFAULT 0,
    xp_earned integer DEFAULT 0,
    is_completed boolean DEFAULT false
);


ALTER TABLE public.practice_sessions OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 33091)
-- Name: practice_sessions_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.practice_sessions_session_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.practice_sessions_session_id_seq OWNER TO postgres;

--
-- TOC entry 5162 (class 0 OID 0)
-- Dependencies: 228
-- Name: practice_sessions_session_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.practice_sessions_session_id_seq OWNED BY public.practice_sessions.session_id;


--
-- TOC entry 227 (class 1259 OID 33077)
-- Name: question_metadata; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question_metadata (
    question_id integer NOT NULL,
    difficulty_level character varying(10),
    embedding_vector jsonb,
    CONSTRAINT question_metadata_difficulty_level_check CHECK (((difficulty_level)::text = ANY ((ARRAY['easy'::character varying, 'medium'::character varying, 'hard'::character varying])::text[])))
);


ALTER TABLE public.question_metadata OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 40963)
-- Name: question_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question_type (
    question_type_id integer NOT NULL,
    type_name text NOT NULL
);


ALTER TABLE public.question_type OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 40972)
-- Name: question_type_question_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.question_type ALTER COLUMN question_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_type_question_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 33056)
-- Name: questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questions (
    question_id integer NOT NULL,
    subject_id integer,
    chapter_id integer,
    question_text text NOT NULL,
    correct_answer text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    options jsonb,
    question_type integer
);


ALTER TABLE public.questions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 33055)
-- Name: questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.questions_question_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.questions_question_id_seq OWNER TO postgres;

--
-- TOC entry 5163 (class 0 OID 0)
-- Dependencies: 225
-- Name: questions_question_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.questions_question_id_seq OWNED BY public.questions.question_id;


--
-- TOC entry 235 (class 1259 OID 33153)
-- Name: recommendations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recommendations (
    recommendation_id integer NOT NULL,
    user_id integer,
    chapter_id integer,
    recommendation_text text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.recommendations OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 33152)
-- Name: recommendations_recommendation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.recommendations_recommendation_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.recommendations_recommendation_id_seq OWNER TO postgres;

--
-- TOC entry 5164 (class 0 OID 0)
-- Dependencies: 234
-- Name: recommendations_recommendation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.recommendations_recommendation_id_seq OWNED BY public.recommendations.recommendation_id;


--
-- TOC entry 231 (class 1259 OID 33110)
-- Name: session_responses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.session_responses (
    response_id integer NOT NULL,
    session_id integer,
    question_id integer,
    is_correct boolean,
    time_taken_seconds integer,
    given_answer text,
    chapter_id integer,
    xp_awarded integer DEFAULT 0
);


ALTER TABLE public.session_responses OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 33109)
-- Name: session_responses_response_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.session_responses_response_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.session_responses_response_id_seq OWNER TO postgres;

--
-- TOC entry 5165 (class 0 OID 0)
-- Dependencies: 230
-- Name: session_responses_response_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.session_responses_response_id_seq OWNED BY public.session_responses.response_id;


--
-- TOC entry 222 (class 1259 OID 33033)
-- Name: subjects; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subjects (
    subject_id integer NOT NULL,
    subject_name character varying(100) NOT NULL,
    description text,
    slug character varying(120),
    icon character varying(80) DEFAULT 'menu_book'::character varying,
    color_class character varying(120) DEFAULT 'bg-primary/10 text-primary'::character varying
);


ALTER TABLE public.subjects OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 33032)
-- Name: subjects_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.subjects_subject_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.subjects_subject_id_seq OWNER TO postgres;

--
-- TOC entry 5166 (class 0 OID 0)
-- Dependencies: 221
-- Name: subjects_subject_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.subjects_subject_id_seq OWNED BY public.subjects.subject_id;


--
-- TOC entry 233 (class 1259 OID 33128)
-- Name: user_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_progress (
    progress_id integer NOT NULL,
    user_id integer,
    subject_id integer,
    chapter_id integer,
    total_attempts integer DEFAULT 0,
    correct_answers integer DEFAULT 0,
    weakness_score double precision
);


ALTER TABLE public.user_progress OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 33127)
-- Name: user_progress_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_progress_progress_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_progress_progress_id_seq OWNER TO postgres;

--
-- TOC entry 5167 (class 0 OID 0)
-- Dependencies: 232
-- Name: user_progress_progress_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_progress_progress_id_seq OWNED BY public.user_progress.progress_id;


--
-- TOC entry 239 (class 1259 OID 41051)
-- Name: user_xp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_xp (
    xp_id integer NOT NULL,
    user_id integer NOT NULL,
    total_xp integer DEFAULT 0 NOT NULL,
    level integer DEFAULT 1 NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.user_xp OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 41050)
-- Name: user_xp_xp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_xp_xp_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_xp_xp_id_seq OWNER TO postgres;

--
-- TOC entry 5168 (class 0 OID 0)
-- Dependencies: 238
-- Name: user_xp_xp_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_xp_xp_id_seq OWNED BY public.user_xp.xp_id;


--
-- TOC entry 220 (class 1259 OID 33018)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    full_name character varying(100),
    email character varying(100) NOT NULL,
    password_hash text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    avatar_url text,
    google_id character varying(255),
    role character varying(20) DEFAULT 'student'::character varying,
    refresh_token text,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['student'::character varying, 'admin'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 33017)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_user_id_seq OWNER TO postgres;

--
-- TOC entry 5169 (class 0 OID 0)
-- Dependencies: 219
-- Name: users_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_user_id_seq OWNED BY public.users.user_id;


--
-- TOC entry 4911 (class 2604 OID 33045)
-- Name: chapters chapter_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chapters ALTER COLUMN chapter_id SET DEFAULT nextval('public.chapters_chapter_id_seq'::regclass);


--
-- TOC entry 4916 (class 2604 OID 33095)
-- Name: practice_sessions session_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.practice_sessions ALTER COLUMN session_id SET DEFAULT nextval('public.practice_sessions_session_id_seq'::regclass);


--
-- TOC entry 4914 (class 2604 OID 33059)
-- Name: questions question_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions ALTER COLUMN question_id SET DEFAULT nextval('public.questions_question_id_seq'::regclass);


--
-- TOC entry 4926 (class 2604 OID 33156)
-- Name: recommendations recommendation_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendations ALTER COLUMN recommendation_id SET DEFAULT nextval('public.recommendations_recommendation_id_seq'::regclass);


--
-- TOC entry 4921 (class 2604 OID 33113)
-- Name: session_responses response_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_responses ALTER COLUMN response_id SET DEFAULT nextval('public.session_responses_response_id_seq'::regclass);


--
-- TOC entry 4908 (class 2604 OID 33036)
-- Name: subjects subject_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subjects ALTER COLUMN subject_id SET DEFAULT nextval('public.subjects_subject_id_seq'::regclass);


--
-- TOC entry 4923 (class 2604 OID 33131)
-- Name: user_progress progress_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_progress ALTER COLUMN progress_id SET DEFAULT nextval('public.user_progress_progress_id_seq'::regclass);


--
-- TOC entry 4928 (class 2604 OID 41054)
-- Name: user_xp xp_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_xp ALTER COLUMN xp_id SET DEFAULT nextval('public.user_xp_xp_id_seq'::regclass);


--
-- TOC entry 4905 (class 2604 OID 33021)
-- Name: users user_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN user_id SET DEFAULT nextval('public.users_user_id_seq'::regclass);


--
-- TOC entry 5140 (class 0 OID 33042)
-- Dependencies: 224
-- Data for Name: chapters; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chapters (chapter_id, subject_id, chapter_name, order_num, description, is_locked) FROM stdin;
1	1	Algebra	1	Equations, expressions, variables and algebraic thinking.	f
2	1	Geometry	2	Shapes, angles, area, perimeter and spatial reasoning.	f
3	2	Physics	1	Forces, motion, energy and the laws of the universe.	f
4	2	Chemistry	2	Elements, compounds, reactions and the periodic table.	f
5	3	Grammar	1	Parts of speech, sentence structure, tense and punctuation.	f
6	3	Comprehension	2	Reading passages, inference, vocabulary in context.	f
7	4	Programming	1	Variables, loops, conditions and basic algorithms.	f
8	4	Networking	2	IP addressing, protocols, OSI model and internet basics.	f
\.


--
-- TOC entry 5145 (class 0 OID 33092)
-- Dependencies: 229
-- Data for Name: practice_sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.practice_sessions (session_id, user_id, subject_id, start_time, end_time, chapter_id, total_q, correct_count, xp_earned, is_completed) FROM stdin;
4	1	1	2026-04-05 05:19:03.611516+05:45	\N	1	7	0	0	f
5	1	1	2026-04-05 05:19:03.626918+05:45	\N	1	7	0	0	f
6	1	1	2026-04-05 05:19:17.923333+05:45	\N	1	7	0	0	f
7	2	1	2026-04-05 12:26:08.532996+05:45	\N	1	7	0	0	f
8	2	1	2026-04-05 12:26:08.750804+05:45	\N	1	7	0	0	f
9	2	1	2026-04-05 12:27:58.087379+05:45	\N	1	7	0	0	f
10	2	1	2026-04-05 12:27:58.089507+05:45	\N	1	7	0	0	f
11	2	1	2026-04-05 15:16:57.620521+05:45	\N	1	7	0	0	f
12	2	1	2026-04-05 15:16:57.627737+05:45	\N	1	7	0	0	f
13	2	1	2026-04-05 16:12:28.345189+05:45	\N	1	7	0	0	f
14	2	1	2026-04-05 16:12:28.366251+05:45	\N	1	7	0	0	f
\.


--
-- TOC entry 5143 (class 0 OID 33077)
-- Dependencies: 227
-- Data for Name: question_metadata; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.question_metadata (question_id, difficulty_level, embedding_vector) FROM stdin;
1	easy	\N
2	medium	\N
3	easy	\N
4	medium	\N
5	hard	\N
6	easy	\N
7	hard	\N
8	easy	\N
9	medium	\N
10	easy	\N
11	easy	\N
12	medium	\N
13	medium	\N
14	hard	\N
15	easy	\N
16	easy	\N
17	medium	\N
18	medium	\N
19	easy	\N
20	hard	\N
21	medium	\N
22	easy	\N
23	easy	\N
24	medium	\N
25	hard	\N
26	medium	\N
27	easy	\N
28	easy	\N
29	medium	\N
30	easy	\N
31	medium	\N
32	medium	\N
33	easy	\N
34	medium	\N
35	easy	\N
36	medium	\N
37	easy	\N
38	easy	\N
39	easy	\N
40	medium	\N
41	easy	\N
42	medium	\N
43	easy	\N
44	easy	\N
45	easy	\N
46	medium	\N
47	easy	\N
48	medium	\N
49	hard	\N
\.


--
-- TOC entry 5152 (class 0 OID 40963)
-- Dependencies: 236
-- Data for Name: question_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.question_type (question_type_id, type_name) FROM stdin;
1	mcq
2	short
3	fill in the blanks
\.


--
-- TOC entry 5142 (class 0 OID 33056)
-- Dependencies: 226
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.questions (question_id, subject_id, chapter_id, question_text, correct_answer, created_at, options, question_type) FROM stdin;
1	1	1	What is the value of x if 2x = 10?	5	2026-04-04 21:20:34.241229	["3", "4", "5", "6"]	1
2	1	1	Simplify: 3a + 2a	5a	2026-04-04 21:20:34.241229	["6a", "5a", "4a", "3a"]	1
3	1	1	If y = 3x and x = 4, what is y?	12	2026-04-04 21:20:34.241229	["8", "10", "12", "14"]	1
4	1	1	Solve for x: x/4 = 3	12	2026-04-04 21:20:34.241229	\N	2
5	1	1	What is the degree of the polynomial 4x³ + 2x - 1?	3	2026-04-04 21:20:34.241229	["1", "2", "3", "4"]	1
6	1	1	The solution to 5x - 10 = 0 is x = ___.	2	2026-04-04 21:20:34.241229	\N	3
7	1	1	Factor: x² - 9	(x+3)(x-3)	2026-04-04 21:20:34.241229	["(x+3)(x-3)", "(x+9)(x-9)", "(x-3)²", "(x+3)²"]	1
8	1	2	How many sides does a pentagon have?	5	2026-04-04 21:20:34.241229	["4", "5", "6", "7"]	1
9	1	2	Area of a rectangle with length 8 and width 5?	40	2026-04-04 21:20:34.241229	["13", "26", "40", "80"]	1
10	1	2	The sum of angles in a triangle is ___ degrees.	180	2026-04-04 21:20:34.241229	\N	3
11	1	2	A circle has how many degrees?	360	2026-04-04 21:20:34.241229	["90", "180", "270", "360"]	1
12	1	2	Perimeter of a square with side 6?	24	2026-04-04 21:20:34.241229	["12", "18", "24", "36"]	1
13	1	2	What is the formula for the area of a triangle?	1/2 × base × height	2026-04-04 21:20:34.241229	\N	2
14	1	2	The hypotenuse is the longest side in a ___ triangle.	right	2026-04-04 21:20:34.241229	\N	3
15	2	3	What is the SI unit of force?	Newton	2026-04-04 21:20:34.241229	["Joule", "Newton", "Watt", "Pascal"]	1
16	2	3	Speed = Distance / ___.	Time	2026-04-04 21:20:34.241229	\N	3
17	2	3	Which law states F = ma?	Newton's 2nd Law	2026-04-04 21:20:34.241229	["Newton's 1st Law", "Newton's 2nd Law", "Newton's 3rd Law", "Law of Gravitation"]	1
18	2	3	What is the approximate value of gravitational acceleration on Earth?	9.8 m/s²	2026-04-04 21:20:34.241229	["8 m/s²", "9.8 m/s²", "10.5 m/s²", "11 m/s²"]	1
19	2	3	The SI unit of energy is ___.	Joule	2026-04-04 21:20:34.241229	\N	3
20	2	3	What happens to momentum when a net force acts on an object?	Momentum changes	2026-04-04 21:20:34.241229	\N	2
21	2	3	Which type of wave requires a medium to travel?	Sound wave	2026-04-04 21:20:34.241229	["Light wave", "Electromagnetic wave", "Sound wave", "Gamma ray"]	1
22	2	4	Chemical formula of water?	H2O	2026-04-04 21:20:34.241229	["H2O", "CO2", "NaCl", "O2"]	1
23	2	4	pH of a neutral solution is ___.	7	2026-04-04 21:20:34.241229	\N	3
24	2	4	What is the symbol for Gold?	Au	2026-04-04 21:20:34.241229	["Go", "Gd", "Au", "Ag"]	1
25	2	4	Atoms of the same element with different neutrons are called?	Isotopes	2026-04-04 21:20:34.241229	["Ions", "Isotopes", "Allotropes", "Molecules"]	1
26	2	4	What type of bond is formed by sharing electrons?	Covalent bond	2026-04-04 21:20:34.241229	\N	2
27	2	4	NaCl is the chemical name for common ___.	Salt	2026-04-04 21:20:34.241229	\N	3
28	3	5	Which of these is a noun?	Happiness	2026-04-04 21:20:34.241229	["Run", "Beautiful", "Happiness", "Quickly"]	1
29	3	5	Choose the correct verb form: She ___ to school every day.	goes	2026-04-04 21:20:34.241229	["go", "goes", "going", "gone"]	1
30	3	5	A ___ is a word that describes a verb.	Adverb	2026-04-04 21:20:34.241229	\N	3
31	3	5	Identify the tense: "They were playing cricket."	Past Continuous	2026-04-04 21:20:34.241229	["Simple Past", "Past Perfect", "Past Continuous", "Present Perfect"]	1
32	3	5	What punctuation ends a question sentence?	Question mark	2026-04-04 21:20:34.241229	\N	2
33	3	5	The word "quickly" is an ___.	Adverb	2026-04-04 21:20:34.241229	\N	3
34	3	6	What does "benevolent" mean?	Kind and generous	2026-04-04 21:20:34.241229	["Cruel", "Kind and generous", "Angry", "Confused"]	1
35	3	6	A synonym for "happy" is?	Joyful	2026-04-04 21:20:34.241229	["Sad", "Angry", "Joyful", "Tired"]	1
36	3	6	An antonym for "ancient" is?	Modern	2026-04-04 21:20:34.241229	\N	2
37	3	6	What is the main idea of a paragraph usually found in?	The topic sentence	2026-04-04 21:20:34.241229	["The last sentence", "The topic sentence", "The middle", "A footnote"]	1
38	3	6	Inference means drawing a conclusion based on ___ and reasoning.	Evidence	2026-04-04 21:20:34.241229	\N	3
39	4	7	Which symbol is used for comments in Python?	#	2026-04-04 21:20:34.241229	["//", "/*", "#", "--"]	1
40	4	7	What does a loop do?	Repeats a block of code	2026-04-04 21:20:34.241229	["Stops the program", "Repeats a block of code", "Declares a variable", "Defines a function"]	1
41	4	7	In Python, print("Hello") outputs ___.	Hello	2026-04-04 21:20:34.241229	\N	3
42	4	7	What is a variable?	A named storage location that holds a value	2026-04-04 21:20:34.241229	\N	2
43	4	7	Which data type stores True or False?	Boolean	2026-04-04 21:20:34.241229	["Integer", "String", "Boolean", "Float"]	1
44	4	7	The ___ statement is used to make decisions in code.	if	2026-04-04 21:20:34.241229	\N	3
45	4	8	What does IP stand for?	Internet Protocol	2026-04-04 21:20:34.241229	["Internet Protocol", "Internal Process", "Input Port", "Interface Program"]	1
46	4	8	How many layers does the OSI model have?	7	2026-04-04 21:20:34.241229	["4", "5", "7", "8"]	1
47	4	8	HTTP stands for HyperText Transfer ___.	Protocol	2026-04-04 21:20:34.241229	\N	3
48	4	8	Which device connects different networks together?	Router	2026-04-04 21:20:34.241229	["Switch", "Hub", "Router", "Repeater"]	1
49	4	8	DNS converts domain names to ___.	IP addresses	2026-04-04 21:20:34.241229	\N	2
\.


--
-- TOC entry 5151 (class 0 OID 33153)
-- Dependencies: 235
-- Data for Name: recommendations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recommendations (recommendation_id, user_id, chapter_id, recommendation_text, created_at) FROM stdin;
\.


--
-- TOC entry 5147 (class 0 OID 33110)
-- Dependencies: 231
-- Data for Name: session_responses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.session_responses (response_id, session_id, question_id, is_correct, time_taken_seconds, given_answer, chapter_id, xp_awarded) FROM stdin;
1	4	2	\N	\N	\N	1	0
2	4	4	\N	\N	\N	1	0
3	4	3	\N	\N	\N	1	0
4	4	6	\N	\N	\N	1	0
5	4	5	\N	\N	\N	1	0
6	4	7	\N	\N	\N	1	0
7	4	1	\N	\N	\N	1	0
8	5	2	\N	\N	\N	1	0
9	5	4	\N	\N	\N	1	0
10	5	6	\N	\N	\N	1	0
11	5	1	\N	\N	\N	1	0
12	5	5	\N	\N	\N	1	0
13	5	7	\N	\N	\N	1	0
14	5	3	\N	\N	\N	1	0
15	6	4	\N	\N	\N	1	0
16	6	2	\N	\N	\N	1	0
17	6	6	\N	\N	\N	1	0
18	6	1	\N	\N	\N	1	0
19	6	7	\N	\N	\N	1	0
20	6	5	\N	\N	\N	1	0
21	6	3	\N	\N	\N	1	0
22	7	4	\N	\N	\N	1	0
23	7	2	\N	\N	\N	1	0
24	7	3	\N	\N	\N	1	0
25	7	1	\N	\N	\N	1	0
26	7	7	\N	\N	\N	1	0
27	7	5	\N	\N	\N	1	0
28	7	6	\N	\N	\N	1	0
29	8	2	\N	\N	\N	1	0
30	8	4	\N	\N	\N	1	0
31	8	6	\N	\N	\N	1	0
32	8	1	\N	\N	\N	1	0
33	8	5	\N	\N	\N	1	0
34	8	7	\N	\N	\N	1	0
35	8	3	\N	\N	\N	1	0
36	9	2	\N	\N	\N	1	0
37	9	4	\N	\N	\N	1	0
38	9	1	\N	\N	\N	1	0
39	9	3	\N	\N	\N	1	0
40	9	7	\N	\N	\N	1	0
41	9	5	\N	\N	\N	1	0
42	9	6	\N	\N	\N	1	0
43	10	4	\N	\N	\N	1	0
44	10	2	\N	\N	\N	1	0
45	10	1	\N	\N	\N	1	0
46	10	3	\N	\N	\N	1	0
47	10	7	\N	\N	\N	1	0
48	10	5	\N	\N	\N	1	0
49	10	6	\N	\N	\N	1	0
50	11	2	\N	\N	\N	1	0
51	11	4	\N	\N	\N	1	0
52	11	6	\N	\N	\N	1	0
53	11	3	\N	\N	\N	1	0
54	11	7	\N	\N	\N	1	0
55	11	5	\N	\N	\N	1	0
56	11	1	\N	\N	\N	1	0
57	12	2	\N	\N	\N	1	0
58	12	4	\N	\N	\N	1	0
59	12	1	\N	\N	\N	1	0
60	12	6	\N	\N	\N	1	0
61	12	5	\N	\N	\N	1	0
62	12	7	\N	\N	\N	1	0
63	12	3	\N	\N	\N	1	0
64	13	2	\N	\N	\N	1	0
66	13	4	\N	\N	\N	1	0
67	13	1	\N	\N	\N	1	0
68	13	3	\N	\N	\N	1	0
69	13	5	\N	\N	\N	1	0
70	13	7	\N	\N	\N	1	0
71	13	6	\N	\N	\N	1	0
65	14	4	\N	\N	\N	1	0
72	14	2	\N	\N	\N	1	0
73	14	6	\N	\N	\N	1	0
74	14	3	\N	\N	\N	1	0
75	14	7	\N	\N	\N	1	0
76	14	5	\N	\N	\N	1	0
77	14	1	\N	\N	\N	1	0
\.


--
-- TOC entry 5138 (class 0 OID 33033)
-- Dependencies: 222
-- Data for Name: subjects; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subjects (subject_id, subject_name, description, slug, icon, color_class) FROM stdin;
1	Mathematics	Algebra, geometry, calculus and more.	mathematics	calculate	bg-purple-100 text-purple-600
2	Science	Physics, chemistry and natural sciences.	science	science	bg-blue-100 text-blue-600
3	English	Grammar, comprehension and writing skills.	english	menu_book	bg-green-100 text-green-600
4	Computer	Programming, hardware, networks and algorithms.	computer	computer	bg-orange-100 text-orange-600
\.


--
-- TOC entry 5149 (class 0 OID 33128)
-- Dependencies: 233
-- Data for Name: user_progress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_progress (progress_id, user_id, subject_id, chapter_id, total_attempts, correct_answers, weakness_score) FROM stdin;
\.


--
-- TOC entry 5155 (class 0 OID 41051)
-- Dependencies: 239
-- Data for Name: user_xp; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_xp (xp_id, user_id, total_xp, level, updated_at) FROM stdin;
1	1	0	1	2026-04-05 05:18:28.289379
2	2	0	1	2026-04-05 12:09:47.593131
\.


--
-- TOC entry 5136 (class 0 OID 33018)
-- Dependencies: 220
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, full_name, email, password_hash, created_at, avatar_url, google_id, role, refresh_token) FROM stdin;
1	Admin	admin@smartsikshya.com	$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMaGgS3BV/CzHrW1.WqNlHXCJe	2026-04-05 05:18:28.289379	\N	\N	admin	\N
2	Pragun Raj Maskey	pragunmaskeyofficial@gmail.com	\N	2026-04-05 12:09:47.593131	https://lh3.googleusercontent.com/a/ACg8ocLnksMT4oWMfDnicCTj4XBO8xRhUu1wGMFydvGxiwIFDm0R4Mxj=s96-c	103370013229523543190	student	\N
\.


--
-- TOC entry 5170 (class 0 OID 0)
-- Dependencies: 223
-- Name: chapters_chapter_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chapters_chapter_id_seq', 8, true);


--
-- TOC entry 5171 (class 0 OID 0)
-- Dependencies: 228
-- Name: practice_sessions_session_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.practice_sessions_session_id_seq', 14, true);


--
-- TOC entry 5172 (class 0 OID 0)
-- Dependencies: 237
-- Name: question_type_question_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.question_type_question_type_id_seq', 3, true);


--
-- TOC entry 5173 (class 0 OID 0)
-- Dependencies: 225
-- Name: questions_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.questions_question_id_seq', 50, true);


--
-- TOC entry 5174 (class 0 OID 0)
-- Dependencies: 234
-- Name: recommendations_recommendation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recommendations_recommendation_id_seq', 1, false);


--
-- TOC entry 5175 (class 0 OID 0)
-- Dependencies: 230
-- Name: session_responses_response_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.session_responses_response_id_seq', 77, true);


--
-- TOC entry 5176 (class 0 OID 0)
-- Dependencies: 221
-- Name: subjects_subject_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subjects_subject_id_seq', 4, true);


--
-- TOC entry 5177 (class 0 OID 0)
-- Dependencies: 232
-- Name: user_progress_progress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_progress_progress_id_seq', 1, false);


--
-- TOC entry 5178 (class 0 OID 0)
-- Dependencies: 238
-- Name: user_xp_xp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_xp_xp_id_seq', 2, true);


--
-- TOC entry 5179 (class 0 OID 0)
-- Dependencies: 219
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 2, true);


--
-- TOC entry 4945 (class 2606 OID 33049)
-- Name: chapters chapters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chapters
    ADD CONSTRAINT chapters_pkey PRIMARY KEY (chapter_id);


--
-- TOC entry 4956 (class 2606 OID 33098)
-- Name: practice_sessions practice_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.practice_sessions
    ADD CONSTRAINT practice_sessions_pkey PRIMARY KEY (session_id);


--
-- TOC entry 4953 (class 2606 OID 33085)
-- Name: question_metadata question_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_metadata
    ADD CONSTRAINT question_metadata_pkey PRIMARY KEY (question_id);


--
-- TOC entry 4966 (class 2606 OID 40971)
-- Name: question_type question_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_type
    ADD CONSTRAINT question_type_pkey PRIMARY KEY (question_type_id);


--
-- TOC entry 4950 (class 2606 OID 33066)
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (question_id);


--
-- TOC entry 4964 (class 2606 OID 33162)
-- Name: recommendations recommendations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT recommendations_pkey PRIMARY KEY (recommendation_id);


--
-- TOC entry 4959 (class 2606 OID 33116)
-- Name: session_responses session_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_responses
    ADD CONSTRAINT session_responses_pkey PRIMARY KEY (response_id);


--
-- TOC entry 4947 (class 2606 OID 40962)
-- Name: chapters subject_id_chapter_name_UNIQUE; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chapters
    ADD CONSTRAINT "subject_id_chapter_name_UNIQUE" UNIQUE (subject_id, chapter_name);


--
-- TOC entry 4941 (class 2606 OID 33040)
-- Name: subjects subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (subject_id);


--
-- TOC entry 4943 (class 2606 OID 41024)
-- Name: subjects subjects_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_slug_key UNIQUE (slug);


--
-- TOC entry 4962 (class 2606 OID 33136)
-- Name: user_progress user_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_pkey PRIMARY KEY (progress_id);


--
-- TOC entry 4968 (class 2606 OID 41063)
-- Name: user_xp user_xp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_xp
    ADD CONSTRAINT user_xp_pkey PRIMARY KEY (xp_id);


--
-- TOC entry 4970 (class 2606 OID 41065)
-- Name: user_xp user_xp_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_xp
    ADD CONSTRAINT user_xp_user_id_key UNIQUE (user_id);


--
-- TOC entry 4935 (class 2606 OID 33031)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4937 (class 2606 OID 41032)
-- Name: users users_google_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_google_id_key UNIQUE (google_id);


--
-- TOC entry 4939 (class 2606 OID 33029)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4948 (class 1259 OID 41071)
-- Name: idx_questions_chapter; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_questions_chapter ON public.questions USING btree (chapter_id);


--
-- TOC entry 4951 (class 1259 OID 41072)
-- Name: idx_questions_difficulty; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_questions_difficulty ON public.question_metadata USING btree (difficulty_level);


--
-- TOC entry 4957 (class 1259 OID 41073)
-- Name: idx_session_resp_session; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_session_resp_session ON public.session_responses USING btree (session_id);


--
-- TOC entry 4954 (class 1259 OID 41075)
-- Name: idx_sessions_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sessions_user ON public.practice_sessions USING btree (user_id, chapter_id);


--
-- TOC entry 4960 (class 1259 OID 41074)
-- Name: idx_user_progress_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_progress_user ON public.user_progress USING btree (user_id, chapter_id);


--
-- TOC entry 4971 (class 2606 OID 33050)
-- Name: chapters chapters_subject_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chapters
    ADD CONSTRAINT chapters_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(subject_id) ON DELETE CASCADE;


--
-- TOC entry 4976 (class 2606 OID 41037)
-- Name: practice_sessions practice_sessions_chapter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.practice_sessions
    ADD CONSTRAINT practice_sessions_chapter_id_fkey FOREIGN KEY (chapter_id) REFERENCES public.chapters(chapter_id);


--
-- TOC entry 4977 (class 2606 OID 33104)
-- Name: practice_sessions practice_sessions_subject_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.practice_sessions
    ADD CONSTRAINT practice_sessions_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(subject_id);


--
-- TOC entry 4978 (class 2606 OID 33099)
-- Name: practice_sessions practice_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.practice_sessions
    ADD CONSTRAINT practice_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4975 (class 2606 OID 33086)
-- Name: question_metadata question_metadata_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_metadata
    ADD CONSTRAINT question_metadata_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(question_id) ON DELETE CASCADE;


--
-- TOC entry 4972 (class 2606 OID 33072)
-- Name: questions questions_chapter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_chapter_id_fkey FOREIGN KEY (chapter_id) REFERENCES public.chapters(chapter_id);


--
-- TOC entry 4973 (class 2606 OID 40973)
-- Name: questions questions_question_type_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_question_type_fkey FOREIGN KEY (question_type) REFERENCES public.question_type(question_type_id);


--
-- TOC entry 4974 (class 2606 OID 33067)
-- Name: questions questions_subject_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(subject_id);


--
-- TOC entry 4985 (class 2606 OID 33168)
-- Name: recommendations recommendations_chapter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT recommendations_chapter_id_fkey FOREIGN KEY (chapter_id) REFERENCES public.chapters(chapter_id);


--
-- TOC entry 4986 (class 2606 OID 33163)
-- Name: recommendations recommendations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recommendations
    ADD CONSTRAINT recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4979 (class 2606 OID 41043)
-- Name: session_responses session_responses_chapter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_responses
    ADD CONSTRAINT session_responses_chapter_id_fkey FOREIGN KEY (chapter_id) REFERENCES public.chapters(chapter_id);


--
-- TOC entry 4980 (class 2606 OID 33122)
-- Name: session_responses session_responses_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_responses
    ADD CONSTRAINT session_responses_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions(question_id);


--
-- TOC entry 4981 (class 2606 OID 33117)
-- Name: session_responses session_responses_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_responses
    ADD CONSTRAINT session_responses_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.practice_sessions(session_id);


--
-- TOC entry 4982 (class 2606 OID 33147)
-- Name: user_progress user_progress_chapter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_chapter_id_fkey FOREIGN KEY (chapter_id) REFERENCES public.chapters(chapter_id);


--
-- TOC entry 4983 (class 2606 OID 33142)
-- Name: user_progress user_progress_subject_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(subject_id);


--
-- TOC entry 4984 (class 2606 OID 33137)
-- Name: user_progress user_progress_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_progress
    ADD CONSTRAINT user_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- TOC entry 4987 (class 2606 OID 41066)
-- Name: user_xp user_xp_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_xp
    ADD CONSTRAINT user_xp_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


-- Completed on 2026-04-06 15:25:28

--
-- PostgreSQL database dump complete
--

\unrestrict gjw00SRBVXZcIjGgPwKPct40qQ8iWOuEt7DKhWvgLBa3JUnGvoStSpv5vKeSOXb

